name: "Install Prerequisites"

runs:
  using: "composite"
  steps:

    - name: Установка инструментов
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        libgtest-dev \
        xutils-dev \
        cmake \
        clang clang-tidy

    - name: Сборка libgtest
      shell: bash
      run: |
        sudo rm -f /usr/lib/x86_64-linux-gnu/libgtest*.a
        cd /usr/src/googletest
        sudo cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
        sudo make
        sudo make install
        sudo ldconfig

    - name: Установка Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"